# Write your MySQL query statement below


SELECT EMPLOYEE_ID FROM 
EMPLOYEES E WHERE E.EMPLOYEE_ID NOT IN 
(
    SELECT EMPLOYEE_ID FROM SALARIES S WHERE S.EMPLOYEE_ID IS NOT NULL
)
UNION
SELECT EMPLOYEE_ID FROM 
SALARIES S WHERE S.EMPLOYEE_ID NOT IN  
(
    SELECT EMPLOYEE_ID FROM EMPLOYEES E WHERE E.EMPLOYEE_ID IS NOT NULL
)
ORDER BY EMPLOYEE_ID;